<?php

return [
    'school_levels' => [
        'Primary' => [
            'Primary 1',
            'Primary 2',
            'Primary 3',
            'Primary 4',
            'Primary 5',
            'Primary 6',
        ],
        'Junior Secondary' => [
            'JSS 1',
            'JSS 2',
            'JSS 3',
        ],
        'Senior Secondary' => [
            'SS 1',
            'SS 2',
            'SS 3',
        ],
        'University / Higher Institution' => [
            '100 Level',
            '200 Level',
            '300 Level',
            '400 Level',
            '500 Level',
            '600 Level',
            'Postgraduate',
            'Other',
        ],
        'Professional / Other' => [
            'Beginner',
            'Intermediate',
            'Advanced',
            'Other',
        ],
    ],

    'countries' => [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Angola',
        'Argentina',
        'Australia',
        'Austria',
        'Bangladesh',
        'Belgium',
        'Benin',
        'Botswana',
        'Brazil',
        'Burkina Faso',
        'Cameroon',
        'Canada',
        'China',
        'Cote d\'Ivoire',
        'Democratic Republic of the Congo',
        'Egypt',
        'Ethiopia',
        'France',
        'Gambia',
        'Germany',
        'Ghana',
        'India',
        'Indonesia',
        'Ireland',
        'Italy',
        'Japan',
        'Kenya',
        'Liberia',
        'Malaysia',
        'Mali',
        'Morocco',
        'Namibia',
        'Netherlands',
        'Niger',
        'Nigeria',
        'Norway',
        'Pakistan',
        'Philippines',
        'Rwanda',
        'Senegal',
        'Sierra Leone',
        'South Africa',
        'South Sudan',
        'Spain',
        'Tanzania',
        'Togo',
        'Turkey',
        'Uganda',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Zambia',
        'Zimbabwe',
    ],

    'city_suggestions' => [
        'Australia' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'],
        'Benin' => ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey-Calavi'],
        'Cameroon' => ['Douala', 'Yaounde', 'Bamenda', 'Bafoussam'],
        'Canada' => ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa'],
        'Egypt' => ['Cairo', 'Alexandria', 'Giza', 'Mansoura'],
        'Ghana' => ['Accra', 'Kumasi', 'Tamale', 'Cape Coast', 'Tema'],
        'India' => ['Delhi', 'Mumbai', 'Bengaluru', 'Chennai', 'Hyderabad'],
        'Ireland' => ['Dublin', 'Cork', 'Galway', 'Limerick'],
        'Kenya' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
        'Nigeria' => ['Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Kano', 'Benin City', 'Enugu', 'Kaduna', 'Abeokuta', 'Owerri'],
        'Rwanda' => ['Kigali', 'Butare', 'Musanze', 'Rubavu'],
        'South Africa' => ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Gqeberha'],
        'Tanzania' => ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza'],
        'Uganda' => ['Kampala', 'Entebbe', 'Jinja', 'Mbarara'],
        'United Arab Emirates' => ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'],
        'United Kingdom' => ['London', 'Manchester', 'Birmingham', 'Leeds', 'Liverpool'],
        'United States' => ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Washington DC'],
    ],
];
